const ID41 = [
  {"qid": 41, "answer": "사과"},
  {"qid": 41, "answer": "배"},
  {"qid": 41, "answer": "포도"},
  {"qid": 41, "answer": "귤"},
  {"qid": 41, "answer": "오렌지"},
  {"qid": 41, "answer": "복숭아"},
  {"qid": 41, "answer": "자두"},
  {"qid": 41, "answer": "살구"},
  {"qid": 41, "answer": "딸기"},
  {"qid": 41, "answer": "바나나"},
  {"qid": 41, "answer": "수박"},
  {"qid": 41, "answer": "참외"},
  {"qid": 41, "answer": "멜론"},
  {"qid": 41, "answer": "키위"},
  {"qid": 41, "answer": "망고"},
  {"qid": 41, "answer": "파인애플"},
  {"qid": 41, "answer": "체리"},
  {"qid": 41, "answer": "블루베리"},
  {"qid": 41, "answer": "감"},
  {"qid": 41, "answer": "곶감"},
  {"qid": 41, "answer": "무화과"},
  {"qid": 41, "answer": "석류"},
  {"qid": 41, "answer": "유자"},
  {"qid": 41, "answer": "자몽"},
  {"qid": 41, "answer": "레몬"},
  {"qid": 41, "answer": "라임"},
  {"qid": 41, "answer": "깔라만시"},
  {"qid": 41, "answer": "파파야"},
  {"qid": 41, "answer": "코코넛"},
  {"qid": 41, "answer": "두리안"},
  {"qid": 41, "answer": "망고스틴"},
  {"qid": 41, "answer": "람부탄"},
  {"qid": 41, "answer": "리치"},
  {"qid": 41, "answer": "용과"},
  {"qid": 41, "answer": "패션후르츠"},
  {"qid": 41, "answer": "아보카도"},
  {"qid": 41, "answer": "대추"},
  {"qid": 41, "answer": "앵두"},
  {"qid": 41, "answer": "체리"},
  {"qid": 41, "answer": "산딸기"},
  {"qid": 41, "answer": "복분자"},
  {"qid": 41, "answer": "오미자"},
  {"qid": 41, "answer": "오디"},
  {"qid": 41, "answer": "매실"},
  {"qid": 41, "answer": "모과"},
  {"qid": 41, "answer": "한라봉"},
  {"qid": 41, "answer": "레드향"},
  {"qid": 41, "answer": "황금향"},
  {"qid": 41, "answer": "금귤(낑깡)"},
  {"qid": 41, "answer": "샤인머스캣"},
  {"qid": 41, "answer": "거봉"},
  {"qid": 41, "answer": "방울토마토"},
  {"qid": 41, "answer": "토마토"},
  {"qid": 41, "answer": "구아바"},
  {"qid": 41, "answer": "잭프루트"},
  {"qid": 41, "answer": "라즈베리"},
  {"qid": 41, "answer": "용과(드래곤후르츠)"},
  {"qid": 41, "answer": "홍시"},
];

const ID42 = [
  {"qid": 42, "answer": "배추"},
  {"qid": 42, "answer": "무"},
  {"qid": 42, "answer": "양파"},
  {"qid": 42, "answer": "마늘"},
  {"qid": 42, "answer": "대파"},
  {"qid": 42, "answer": "쪽파"},
  {"qid": 42, "answer": "고추"},
  {"qid": 42, "answer": "상추"},
  {"qid": 42, "answer": "깻잎"},
  {"qid": 42, "answer": "시금치"},
  {"qid": 42, "answer": "오이"},
  {"qid": 42, "answer": "당근"},
  {"qid": 42, "answer": "감자"},
  {"qid": 42, "answer": "고구마"},
  {"qid": 42, "answer": "호박"},
  {"qid": 42, "answer": "가지"},
  {"qid": 42, "answer": "브로콜리"},
  {"qid": 42, "answer": "양배추"},
  {"qid": 42, "answer": "양상추"},
  {"qid": 42, "answer": "파프리카"},
  {"qid": 42, "answer": "피망"},
  {"qid": 42, "answer": "부추"},
  {"qid": 42, "answer": "미나리"},
  {"qid": 42, "answer": "청경채"},
  {"qid": 42, "answer": "콩나물"},
  {"qid": 42, "answer": "숙주나물"},
  {"qid": 42, "answer": "고사리"},
  {"qid": 42, "answer": "도라지"},
  {"qid": 42, "answer": "더덕"},
  {"qid": 42, "answer": "우엉"},
  {"qid": 42, "answer": "연근"},
  {"qid": 42, "answer": "콜라비"},
  {"qid": 42, "answer": "아스파라거스"},
  {"qid": 42, "answer": "셀러리"},
  {"qid": 42, "answer": "케일"},
  {"qid": 42, "answer": "치커리"},
  {"qid": 42, "answer": "방울양배추"},
  {"qid": 42, "answer": "토마토"},
  {"qid": 42, "answer": "방울토마토"},
  {"qid": 42, "answer": "죽순"},
  {"qid": 42, "answer": "옥수수"},
  {"qid": 42, "answer": "완두콩"},
  {"qid": 42, "answer": "검은콩"},
  {"qid": 42, "answer": "청양고추"},
  {"qid": 42, "answer": "오이고추"},
  {"qid": 42, "answer": "팽이버섯"},
  {"qid": 42, "answer": "새송이버섯"},
  {"qid": 42, "answer": "갓"},
  {"qid": 42, "answer": "냉이"},
  {"qid": 42, "answer": "쑥"},
  {"qid": 42, "answer": "시래기"},
  {"qid": 42, "answer": "바질"},
  {"qid": 42, "answer": "고수"},
  {"qid": 42, "answer": "파슬리"},
  {"qid": 42, "answer": "로즈마리"},
  {"qid": 42, "answer": "겨자"},
];

// 음식
const ID43 = [
  {"qid": 43, "answer": "비빔밥"},
  {"qid": 43, "answer": "불고기"},
  {"qid": 43, "answer": "김치찌개"},
  {"qid": 43, "answer": "된장찌개"},
  {"qid": 43, "answer": "순두부찌개"},
  {"qid": 43, "answer": "부대찌개"},
  {"qid": 43, "answer": "감자탕"},
  {"qid": 43, "answer": "추어탕"},
  {"qid": 43, "answer": "설렁탕"},
  {"qid": 43, "answer": "곰탕"},
  {"qid": 43, "answer": "갈비탕"},
  {"qid": 43, "answer": "잡채"},
  {"qid": 43, "answer": "떡볶이"},
  {"qid": 43, "answer": "제육볶음"},
  {"qid": 43, "answer": "삼겹살"},
  {"qid": 43, "answer": "차돌박이"},
  {"qid": 43, "answer": "보쌈"},
  {"qid": 43, "answer": "족발"},
  {"qid": 43, "answer": "냉면"},
  {"qid": 43, "answer": "삼계탕"},
  {"qid": 43, "answer": "육개장"},
  {"qid": 43, "answer": "갈비찜"},
  {"qid": 43, "answer": "국밥"},
  {"qid": 43, "answer": "해물파전"},
  {"qid": 43, "answer": "아구찜"},
  {"qid": 43, "answer": "돈가스"},
  {"qid": 43, "answer": "함박스테이크"},
  {"qid": 43, "answer": "까르보나라"},
  {"qid": 43, "answer": "봉골레파스타"},
  {"qid": 43, "answer": "알리오올리오"},
  {"qid": 43, "answer": "마르게리따피자"},
  {"qid": 43, "answer": "고르곤졸라피자"},
  {"qid": 43, "answer": "치즈피자"},
  {"qid": 43, "answer": "페퍼로니피자"},
  {"qid": 43, "answer": "리조또"},
  {"qid": 43, "answer": "라자냐"},
  {"qid": 43, "answer": "감바스"},
  {"qid": 43, "answer": "스테이크"},
  {"qid": 43, "answer": "에그인헬"},
  {"qid": 43, "answer": "프렌치토스트"},
  {"qid": 43, "answer": "클럽샌드위치"},
  {"qid": 43, "answer": "시저샐러드"},
  {"qid": 43, "answer": "짜장면"},
  {"qid": 43, "answer": "짬뽕"},
  {"qid": 43, "answer": "탕수육"},
  {"qid": 43, "answer": "마파두부"},
  {"qid": 43, "answer": "멘보샤"},
  {"qid": 43, "answer": "딤섬"},
  {"qid": 43, "answer": "마라탕"},
  {"qid": 43, "answer": "꿔바로우"},
  {"qid": 43, "answer": "양꼬치"},
  {"qid": 43, "answer": "초밥"},
  {"qid": 43, "answer": "라멘"},
  {"qid": 43, "answer": "우동"},
  {"qid": 43, "answer": "소바"},
  {"qid": 43, "answer": "돈부리"},
  {"qid": 43, "answer": "규동"},
  {"qid": 43, "answer": "가츠동"},
  {"qid": 43, "answer": "타코야끼"},
  {"qid": 43, "answer": "나베"},
  {"qid": 43, "answer": "샤브샤브"},
  {"qid": 43, "answer": "텐동"},
  {"qid": 43, "answer": "쌀국수"},
  {"qid": 43, "answer": "똠양꿍"},
  {"qid": 43, "answer": "타코"},
  {"qid": 43, "answer": "카레"},
  {"qid": 43, "answer": "케밥"},
  {"qid": 43, "answer": "치즈볼"},
  {"qid": 43, "answer": "(BHC)뿌링클"},
  {"qid": 43, "answer": "(BHC)콰상킹"},
  {"qid": 43, "answer": "(멕시카나)신호등치킨"},
  {"qid": 43, "answer": "(BBQ)자메이카통다리"},
  {"qid": 43, "answer": "(BBQ)황금올리브"},
  {"qid": 43, "answer": "(교촌)허니콤보"},
  {"qid": 43, "answer": "(굽네)갈비천왕"},
  {"qid": 43, "answer": "(굽네)고추바사삭"},
  {"qid": 43, "answer": "(처갓집)슈프림양념"},
  {"qid": 43, "answer": "양념치킨"},
  {"qid": 43, "answer": "빅맥"},
  {"qid": 43, "answer": "새우버거"},
  {"qid": 43, "answer": "치즈버거"},
  {"qid": 43, "answer": "와퍼"},
  {"qid": 43, "answer": "불고기버거"},
  {"qid": 43, "answer": "싸이버거"},
  {"qid": 43, "answer": "군대리아"},
  {"qid": 43, "answer": "핫도그"},
  {"qid": 43, "answer": "김치볶음밥"},
  {"qid": 43, "answer": "칼국수"},
  {"qid": 43, "answer": "간장게장"},
  {"qid": 43, "answer": "회"},
  {"qid": 43, "answer": "찜닭"},
];

const ID44 = [
  {"qid": 44, "answer": "세종대왕"},
  {"qid": 44, "answer": "퇴계 이황"},
  {"qid": 44, "answer": "이순신"},
  {"qid": 44, "answer": "이성계"},
  {"qid": 44, "answer": "유재석"},
  {"qid": 44, "answer": "강호동"},
  {"qid": 44, "answer": "이종석"},
  {"qid": 44, "answer": "유관순"},
  {"qid": 44, "answer": "침착맨"},
  {"qid": 44, "answer": "빠니보틀"},
  {"qid": 44, "answer": "주우재"},
  {"qid": 44, "answer": "(진격의거인)에렌 예거"},
  {"qid": 44, "answer": "(원피스)루피"},
  {"qid": 44, "answer": "(귀멸의칼날)렌고쿠"},
  {"qid": 44, "answer": "둘리"},
  {"qid": 44, "answer": "짱구"},

  {"qid": 44, "answer": "제니"},
  {"qid": 44, "answer": "로제"},
  {"qid": 44, "answer": "장원영"},
  {"qid": 44, "answer": "카리나"},
  {"qid": 44, "answer": "차은우"},
  {"qid": 44, "answer": "지드래곤"},
  {"qid": 44, "answer": "피오"},
  {"qid": 44, "answer": "덱스"},
  {"qid": 44, "answer": "곽튜브"},
  {"qid": 44, "answer": "백종원"},
  {"qid": 44, "answer": "기안84"},
  {"qid": 44, "answer": "손흥민"},
  {"qid": 44, "answer": "페이커"},
  {"qid": 44, "answer": "서장훈"},
  {"qid": 44, "answer": "로버트 다우니 주니어"},
  {"qid": 44, "answer": "스칼렛 요한슨"},
  {"qid": 44, "answer": "브래드 피트"},
  {"qid": 44, "answer": "톰 크루즈"},
  {"qid": 44, "answer": "덤블도어"},
  {"qid": 44, "answer": "도라에몽"},
  {"qid": 44, "answer": "흰둥이"},
  {"qid": 44, "answer": "(포켓몬스터)지우"},
  {"qid": 44, "answer": "나루토"},
  {"qid": 44, "answer": "(진격의거인)리바이"},
  {"qid": 44, "answer": "강백호"},
  {"qid": 44, "answer": "엘사"},
  {"qid": 44, "answer": "올라프"},
  {"qid": 44, "answer": "곰돌이 푸"},
  {"qid": 44, "answer": "스폰지밥"},
  {"qid": 44, "answer": "뚱이"},
  {"qid": 44, "answer": "징징이"},
  {"qid": 44, "answer": "뽀로로"},
  {"qid": 44, "answer": "마동석"},
  {"qid": 44, "answer": "손석구"},
  {"qid": 44, "answer": "최민식"},
  {"qid": 44, "answer": "송강호"},
  {"qid": 44, "answer": "이정재"},
  {"qid": 44, "answer": "한소희"},
  {"qid": 44, "answer": "김태리"},
  {"qid": 44, "answer": "공유"},
  {"qid": 44, "answer": "박보검"},
  {"qid": 44, "answer": "테일러 스위프트"},
  {"qid": 44, "answer": "저스틴 비버"},
  {"qid": 44, "answer": "아리아나 그란데"},
  {"qid": 44, "answer": "브루노 마스"},
  {"qid": 44, "answer": "찰리 푸스"},
];

const ID45 = [
  {"qid": 45, "answer": "개"},
  {"qid": 45, "answer": "고양이"},
  {"qid": 45, "answer": "토끼"},
  {"qid": 45, "answer": "다람쥐"},
  {"qid": 45, "answer": "쥐"},
  {"qid": 45, "answer": "다람쥐"},
  {"qid": 45, "answer": "햄스터"},
  {"qid": 45, "answer": "사자"},
  {"qid": 45, "answer": "호랑이"},
  {"qid": 45, "answer": "코끼리"},
  {"qid": 45, "answer": "기린"},
  {"qid": 45, "answer": "얼룩말"},
  {"qid": 45, "answer": "하마"},
  {"qid": 45, "answer": "코뿔소"},
  {"qid": 45, "answer": "곰"},
  {"qid": 45, "answer": "팬더"},
  {"qid": 45, "answer": "늑대"},
  {"qid": 45, "answer": "여우"},
  {"qid": 45, "answer": "사막여우"},
  {"qid": 45, "answer": "원숭이"},
  {"qid": 45, "answer": "고릴라"},
  {"qid": 45, "answer": "침팬지"},
  {"qid": 45, "answer": "오랑우탄"},
  {"qid": 45, "answer": "나무늘보"},
  {"qid": 45, "answer": "코알라"},
  {"qid": 45, "answer": "캥거루"},
  {"qid": 45, "answer": "쿼카"},
  {"qid": 45, "answer": "카피바라"},
  {"qid": 45, "answer": "수달"},
  {"qid": 45, "answer": "비버"},
  {"qid": 45, "answer": "사슴"},
  {"qid": 45, "answer": "고라니"},
  {"qid": 45, "answer": "멧돼지"},
  {"qid": 45, "answer": "독수리"},
  {"qid": 45, "answer": "올빼미"},
  {"qid": 45, "answer": "까치"},
  {"qid": 45, "answer": "까마귀"},
  {"qid": 45, "answer": "비둘기"},
  {"qid": 45, "answer": "참새"},
  {"qid": 45, "answer": "펭귄"},
  {"qid": 45, "answer": "타조"},
  {"qid": 45, "answer": "앵무새"},
  {"qid": 45, "answer": "닭"},
  {"qid": 45, "answer": "오리"},
  {"qid": 45, "answer": "거위"},
  {"qid": 45, "answer": "병아리"},
  {"qid": 45, "answer": "고래"},
  {"qid": 45, "answer": "돌고래"},
  {"qid": 45, "answer": "상어"},
  {"qid": 45, "answer": "불가사리"},
  {"qid": 45, "answer": "연어"},
  {"qid": 45, "answer": "거북이"},
  {"qid": 45, "answer": "오징어"},
  {"qid": 45, "answer": "해파리"},
  {"qid": 45, "answer": "꽃게"},
  {"qid": 45, "answer": "가오리"},
  {"qid": 45, "answer": "물개"},
  {"qid": 45, "answer": "바다사자"},
  {"qid": 45, "answer": "바다코끼리"},
  {"qid": 45, "answer": "악어"},
  {"qid": 45, "answer": "전기뱀장어"},
  {"qid": 45, "answer": "뱀"},
  {"qid": 45, "answer": "도마뱀"},
  {"qid": 45, "answer": "카멜레온"},
  {"qid": 45, "answer": "개구리"},
  {"qid": 45, "answer": "두꺼비"},
  {"qid": 45, "answer": "달팽이"},
  {"qid": 45, "answer": "지렁이"},
  {"qid": 45, "answer": "나비"},
  {"qid": 45, "answer": "벌"},
  {"qid": 45, "answer": "무당벌레"},
  {"qid": 45, "answer": "잠자리"},
  {"qid": 45, "answer": "매미"},
  {"qid": 45, "answer": "사마귀"},
  {"qid": 45, "answer": "메뚜기"},
  {"qid": 45, "answer": "개미"},
  {"qid": 45, "answer": "거미"},
  {"qid": 45, "answer": "말"},
  {"qid": 45, "answer": "소"},
  {"qid": 45, "answer": "돼지"},
  {"qid": 45, "answer": "양"},
  {"qid": 45, "answer": "염소"},
  {"qid": 45, "answer": "낙타"},
  {"qid": 45, "answer": "알파카"},
  {"qid": 45, "answer": "순록"},
  {"qid": 45, "answer": "티라노사우루스"},
  {"qid": 45, "answer": "유니콘"},
  {"qid": 45, "answer": "용"},
];

const ID46 = [
  {"qid": 46, "answer": "기생충"},
  {"qid": 46, "answer": "극한직업"},
  {"qid": 46, "answer": "범죄도시"},
  {"qid": 46, "answer": "서울의 봄"},
  {"qid": 46, "answer": "파묘"},
  {"qid": 46, "answer": "아바타"},
  {"qid": 46, "answer": "어벤져스"},
  {"qid": 46, "answer": "겨울왕국"},
  {"qid": 46, "answer": "알라딘"},
  {"qid": 46, "answer": "엘리멘탈"},
  {"qid": 46, "answer": "부산행"},
  {"qid": 46, "answer": "신과함께"},
  {"qid": 46, "answer": "탑건: 매버릭"},
  {"qid": 46, "answer": "오펜하이머"},
  {"qid": 46, "answer": "인터스텔라"},
  {"qid": 46, "answer": "인셉션"},
  {"qid": 46, "answer": "조커"},
  {"qid": 46, "answer": "라라랜드"},
  {"qid": 46, "answer": "보헤미안 랩소디"},
  {"qid": 46, "answer": "어바웃 타임"},
  {"qid": 46, "answer": "베테랑"},
  {"qid": 46, "answer": "도둑들"},
  {"qid": 46, "answer": "암살"},
  {"qid": 46, "answer": "너의 이름은."},
  {"qid": 46, "answer": "스즈메의 문단속"},
  {"qid": 46, "answer": "센과 치히로의 행방불명"},
  {"qid": 46, "answer": "스파이더맨"},
  {"qid": 46, "answer": "닥터 스트레인지"},
  {"qid": 46, "answer": "가디언즈 오브 갤럭시"},
  {"qid": 46, "answer": "블랙 팬서"},
  {"qid": 46, "answer": "아이언맨"},
  {"qid": 46, "answer": "해리 포터"},
  {"qid": 46, "answer": "반지의 제왕"},
  {"qid": 46, "answer": "헝거게임"},
  {"qid": 46, "answer": "메이즈 러너"},
  {"qid": 46, "answer": "트와일라잇"},
  {"qid": 46, "answer": "곡성"},
  {"qid": 46, "answer": "신세계"},
  {"qid": 46, "answer": "범죄와의 전쟁"},
  {"qid": 46, "answer": "택시운전자"},
  {"qid": 46, "answer": "변호인"},
  {"qid": 46, "answer": "국제시장"},
  {"qid": 46, "answer": "관상"},
  {"qid": 46, "answer": "주온"},
  {"qid": 46, "answer": "엑시트"},
  {"qid": 46, "answer": "청년경찰"},
  {"qid": 46, "answer": "스물"},
  {"qid": 46, "answer": "써니"},
  {"qid": 46, "answer": "건축학개론"},
  {"qid": 46, "answer": "귀멸의 칼날 : 무한성"},
  {"qid": 46, "answer": "너의 췌장을 먹고싶어"},
  {"qid": 46, "answer": "킹스맨"},
  {"qid": 46, "answer": "미션 임파서블"},
  {"qid": 46, "answer": "분노의 질주"},
  {"qid": 46, "answer": "찰리와 초콜릿공장"},
  {"qid": 46, "answer": "인사이드 아웃"},
  {"qid": 46, "answer": "토이 스토리"},
  {"qid": 46, "answer": "미니언즈"},
  {"qid": 46, "answer": "하울의 움직이는 성"},
  {"qid": 46, "answer": "이웃집 토토로"},
  {"qid": 46, "answer": "벼랑 위의 포뇨"},
  {"qid": 46, "answer": "날씨의 아이"},
  {"qid": 46, "answer": "공조"},
  {"qid": 46, "answer": "분노의 질주"},
  {"qid": 46, "answer": "쥬라기 월드"},
  {"qid": 46, "answer": "캐리비안의 해적"},
  {"qid": 46, "answer": "트랜스포머"},
  {"qid": 46, "answer": "주토피아"},
  {"qid": 46, "answer": "코코"},
  {"qid": 46, "answer": "업"},
  {"qid": 46, "answer": "라푼젤"},
  {"qid": 46, "answer": "모아나"},
];
